### ISSUE TITLE
Constellations Project DVP

### ISSUE THREAD

**Issue by asadmehdi785** [neepshed/dvp-u3-constellations#1]
### Criteria 1: Matplotlib and CSV
* _Score Level:_ **4** 
* _Comment(s):_ The Jupyter notebook file imports the libraries necessary for the project.
 
### Criteria 2: Implementation of 2D Visualization
* _Score Level:_ **4**
* _Comment(s):_ The 2D grid appears with data plotted on the graph and the visualization includes custom color.
 
### Criteria 3: Implementation of 3D Visualization
* _Score Level:_ **4**
* _Comment(s):_ The 3D grid appears with the correct data plotted on the graph. The grid is rotatable.
 
### Overall Score: 12/12
Great job with this project! The only issue I really noticed was the lack of titles on the 2D and 3D visualizations, although I saw that you did try to add them in your code. I'm not exactly sure what the issue was there, as when I uncommented the code to add the titles it seemed to work out for me. However, I gave you full credit on those parts anyways since you did an excellent job with customizing the colors and markers.

I hope you enjoy the rest of the course!

**Comment by neepshed** [comment]
Thank you for the feedback.
